services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: 'sqlserver'
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
        - bridge      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq       
    networks:
        - bridge
  tarefasapi:
    image: emjb1973/tarefasapiimg:latest
    container_name: 'tarefasapi'
    build:
      context: tarefasapi
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8000
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
        - bridge
  tarefasui:
    image: emjb1973/tarefasangularimg:latest
    container_name: 'tarefasui'
    ports:
        - 4200:4200
    networks:
        - bridge
networks:
  bridge:
    driver: bridge  
